sudo: false
language: node_js
node_js:
  - "6.0"

cache:
  directories:
    - node_modules
addons:
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
